# Site settings
title: Your awesome title
email: robinsta@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog.  This is going to be a test bed for lots
  of things.  I might write.  I might post photos.  I am trying to learn
  Github pages and generally keep learning. Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://robinsta.github.io" # the base hostname & protocol for your site
twitter_username: robinsta5967
github_username:  robinsta

# Build settings
markdown: kramdown
